apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-streams
  name: hello-world-streams
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-streams
  template:
    metadata:
      labels:
        app: hello-world-streams
    spec:
      containers:
      - name: hello-world-streams
        imagePullPolicy: Always
        image: frawless/hello-world-streams:demo-telegram
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: APPLICATION_ID
            value: hello-world-streams
          - name: SOURCE_TOPIC
            value: telegram-topic-source
          - name: TARGET_TOPIC
            value: telegram-topic-sink
          - name: LOG_LEVEL
            value: "INFO"
          - name: ADDITIONAL_CONFIG
            value: |
              retries=100
